from django.urls import path

from api.views import (
    AdminLoginView,
    AdminProfileView,
    AdminRegisterView,
    LogoutView,
    MeView,
    StaffLoginView,
    VerifyPasswordView,
)
from api.views.catalog import (
    QuestionDetailView,
    QuestionListCreateView,
    QuestionStatusView,
    SchoolDetailView,
    SchoolListCreateView,
    SchoolStatusView,
    SponsorDetailView,
    SponsorListCreateView,
    SubjectDetailView,
    SubjectListCreateView,
    SubjectStatusView,
)
from api.views.competitions import (
    AssignControllerView,
    AssignHostView,
    CompetitionDetailView,
    CompetitionListCreateView,
    CompetitionSchoolsView,
    FixtureGenerateView,
    FixtureGetView,
    FixtureRegenerateView,
    MatchDetailView,
    MatchListView,
    PublicCompetitionListView,
    StaffDetailView,
)
from api.views.dashboard import (
    DashboardView,
    ReportCreateView,
    ReportDetailView,
    ReportFileView,
    TemplateDownloadView,
    TemplateUploadView,
)
from api.views.live import (
    CompetitionResultsView,
    ControllerModeView,
    FinalizeMatchView,
    HostModeView,
    LiveStateView,
    MatchResultView,
    PublicStateStreamView,
    PublicStateView,
    QuestionResultView,
    SelectQuestionView,
    SelectSchoolView,
    SelectSubjectView,
    TimerView,
    VideoQuestionListView,
)

urlpatterns = [
    path("auth/admin/register", AdminRegisterView.as_view()),
    path("auth/admin/login", AdminLoginView.as_view()),
    path("auth/staff/login", StaffLoginView.as_view()),
    path("auth/me", MeView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("admin/profile", AdminProfileView.as_view()),
    path("admin/profile/verify-password", VerifyPasswordView.as_view()),
    path("admin/dashboard", DashboardView.as_view()),
    path("schools", SchoolListCreateView.as_view()),
    path("schools/<uuid:pk>", SchoolDetailView.as_view()),
    path("schools/<uuid:pk>/status", SchoolStatusView.as_view()),
    path("subjects", SubjectListCreateView.as_view()),
    path("subjects/<uuid:pk>", SubjectDetailView.as_view()),
    path("subjects/<uuid:pk>/status", SubjectStatusView.as_view()),
    path("questions/templates/download", TemplateDownloadView.as_view()),
    path("questions/templates/upload", TemplateUploadView.as_view()),
    path("questions", QuestionListCreateView.as_view()),
    path("questions/<uuid:pk>", QuestionDetailView.as_view()),
    path("questions/<uuid:pk>/status", QuestionStatusView.as_view()),
    path("sponsors", SponsorListCreateView.as_view()),
    path("sponsors/<uuid:pk>", SponsorDetailView.as_view()),
    path("competitions/public", PublicCompetitionListView.as_view()),
    path("competitions", CompetitionListCreateView.as_view()),
    path("competitions/<uuid:pk>", CompetitionDetailView.as_view()),
    path("competitions/<uuid:pk>/schools", CompetitionSchoolsView.as_view()),
    path("competitions/<uuid:pk>/host", AssignHostView.as_view()),
    path("competitions/<uuid:pk>/controller", AssignControllerView.as_view()),
    path("competitions/<uuid:pk>/fixtures/generate", FixtureGenerateView.as_view()),
    path("competitions/<uuid:pk>/fixtures/regenerate", FixtureRegenerateView.as_view()),
    path("competitions/<uuid:pk>/fixtures", FixtureGetView.as_view()),
    path("competitions/<uuid:pk>/results", CompetitionResultsView.as_view()),
    path("competitions/<uuid:pk>/reports", ReportCreateView.as_view()),
    path("staff/<uuid:pk>", StaffDetailView.as_view()),
    path("matches", MatchListView.as_view()),
    path("matches/<uuid:pk>/live-state", LiveStateView.as_view()),
    path("matches/<uuid:pk>/select-school", SelectSchoolView.as_view()),
    path("matches/<uuid:pk>/select-subject", SelectSubjectView.as_view()),
    path("matches/<uuid:pk>/select-question", SelectQuestionView.as_view()),
    path("matches/<uuid:pk>/timer", TimerView.as_view()),
    path("matches/<uuid:pk>/question-result", QuestionResultView.as_view()),
    path("matches/<uuid:pk>/mode", HostModeView.as_view()),
    path("matches/<uuid:pk>/video-questions", VideoQuestionListView.as_view()),
    path("matches/<uuid:pk>/public-state/stream", PublicStateStreamView.as_view()),
    path("matches/<uuid:pk>/public-state", PublicStateView.as_view()),
    path("matches/<uuid:pk>/controller-mode", ControllerModeView.as_view()),
    path("matches/<uuid:pk>/result", MatchResultView.as_view()),
    path("matches/<uuid:pk>/finalize", FinalizeMatchView.as_view()),
    path("matches/<uuid:pk>", MatchDetailView.as_view()),
    path("reports/<uuid:report_id>/file", ReportFileView.as_view()),
    path("reports/<uuid:report_id>", ReportDetailView.as_view()),
]
